import thumbnail from '../assets/thumbnail.jpeg'
// import thumbnail from "./assets/thumbnail.jpg"; // update path if needed

const trendingData = [
  {
    id: 1,
    src: "video1.mp4",
    title: "Big Video Title",
    description: "Description for video 1",
    thumbnail: thumbnail,
    channelAvatar: thumbnail,
    channelName: "Channel 1",
    views: "1M views",
    uploaded: "1 day ago",
  },
  {
    id: 2,
    src: "video2.mp4",
    width: "w-[18rem]",
    height: "h-[28rem]",
    title: "Vertical Clip",
    description: "Description for video 2",
    thumbnail: thumbnail,
    channelAvatar: thumbnail,
    channelName: "Channel 2",
    views: "800K views",
    uploaded: "3 days ago",
  },
  {
    id: 3,
    src: "video3.mp4",
    width: "w-[16rem]",
    height: "h-[26rem]",
    title: "Shorts Reel",
    description: "Description for video 3",
    thumbnail: thumbnail,
    channelAvatar: thumbnail,
    channelName: "Channel 3",
    views: "550K views",
    uploaded: "5 days ago",
  },
  {
    id: 4,
    src: "video4.mp4",
    width: "w-[14rem]",
    height: "h-[14rem]",
    title: "Mini Clip",
    description: "Description for video 4",
    thumbnail: thumbnail,
    channelAvatar: thumbnail,
    channelName: "Channel 4",
    views: "200K views",
    uploaded: "1 week ago",
  },
  {
    id: 5,
    src: "video5.mp4",
    width: "w-[28rem]",
    height: "h-[18rem]",
    title: "Wide Highlight",
    description: "Description for video 5",
    thumbnail: thumbnail,
    channelAvatar: thumbnail,
    channelName: "Channel 5",
    views: "1.2M views",
    uploaded: "2 weeks ago",
  },
  {
    id: 6,
    src: "video6.mp4",
    width: "w-[16rem]",
    height: "h-[14rem]",
    title: "Trending Shot",
    description: "Description for video 6",
    thumbnail: thumbnail,
    channelAvatar: thumbnail,
    channelName: "Channel 6",
    views: "940K views",
    uploaded: "6 days ago",
  },
  {
    id: 7,
    src: "video7.mp4",
    width: "w-[30rem]",
    height: "h-[20rem]",
    title: "Deep Dive",
    description: "Description for video 7",
    thumbnail: thumbnail,
    channelAvatar: thumbnail,
    channelName: "Channel 7",
    views: "720K views",
    uploaded: "3 weeks ago",
  },
  {
    id: 8,
    src: "video8.mp4",
    width: "w-[16rem]",
    height: "h-[16rem]",
    title: "Funny Short",
    description: "Description for video 8",
    thumbnail: thumbnail,
    channelAvatar: thumbnail,
    channelName: "Channel 8",
    views: "1.5M views",
    uploaded: "2 days ago",
  },
  {
    id: 9,
    src: "video9.mp4",
    width: "w-[20rem]",
    height: "h-[22rem]",
    title: "AI Explainer",
    description: "Description for video 9",
    thumbnail: thumbnail,
    channelAvatar: thumbnail,
    channelName: "Channel 9",
    views: "300K views",
    uploaded: "4 days ago",
  },
  {
    id: 10,
    src: "video10.mp4",
    width: "w-[22rem]",
    height: "h-[20rem]",
    title: "React Tutorial",
    description: "Description for video 10",
    thumbnail: thumbnail,
    channelAvatar: thumbnail,
    channelName: "Channel 10",
    views: "2.1M views",
    uploaded: "1 month ago",
  },
];

export default trendingData;
